### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by da3dsoul1** [sumguytho/SpiralKnightsMods#1]
First of all thank you for the mods, but i'm really sorry, I'm not a tech savvy user. how do I use them on windows? Where should I put the .jar files

**Comment by sumguytho** [comment]
Hey, sorry for the prolonged silence, that's none of your fault that you couldn't launch this on Windows, in fact, this whole project is mostly work in progress, I still haven't figured out a lot of stuff , launching mods on Windows included. I thought I'd quickly make a script for that and that's it, but since I haven't done anything for Windows in quite a while I forgot that doing something quickly isn't about Windows. The launching will be somewhat arcane because of all the decisions i made but the script will be there sometime in the near future.

**Comment by da3dsoul1** [comment]
I see, thank you! I also found some other code-mods from this repo: https://github.com/spiralstudio/mods , they are working fine with a knightlauncher fork version that support code-mods. For some reason your mods don't work with it. Will be waiting for your future progress!

**Comment by sumguytho** [comment]
Hey there, I've modified mods to compile for JRE 1.6 and as a result they should now work fine with JVM that Spiral Knights is shipped with for Windows and perhaps even with launcher from yihleego's fork. I've also added a python script that launches Spiral Knights with mods, check readme for details.
